### ISSUE TITLE
ui-panel-button-padding doesn't work with the official release of xd 20

### ISSUE THREAD

**Issue by alexdobsom** [AdobeXD/plugin-samples#47]
@kerrishotts 
btw, nor the prerelease version. It just doesn't show up in the plugin panel

**Comment by dkstevekwak** [comment]
@alexdobsom In the general release, this sample won't work because it's a plugin built for the future XD 21 general release. This should work in the plugin prerelease (note that there is a general prerelease vs plugin panel release). What prerelease version are you on? You can go to XD > about XD to get the version number.

**Comment by ashryanbeats** [comment]
This may have stemmed from confusion about which version to try the sample in. At this point, I can confirm the sample plugin shows up and works with XD 21.

I'm closing this issue. Please reopen if you're still experiencing issues.
